# -*- coding: utf-8 -*-
"""Transcript Summarization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11GF-hX0ifp-SSHuZFu2yqkaSMWwcGvWI
"""

!pip install -q transformers

!pip install -q youtube_transcript_api

from transformers import pipeline
from youtube_transcript_api import YouTubeTranscriptApi

youtube_video = "https://www.youtube.com/watch?v=aOL7wzEIZSc"

video_id = youtube_video.split("=")[1]

video_id

from IPython.display import YouTubeVideo
YouTubeVideo(video_id)

YouTubeTranscriptApi.get_transcript(video_id)
transcript = YouTubeTranscriptApi.get_transcript(video_id)

transcript[0:5]

result = ""
for i in transcript:
    result += ' ' + i['text']
#print(result)
print(len(result))

summarizer = pipeline('summarization' ,model = 't5-base', framework ='tf')

num_iters = int(len(result)/1500)
summarized_text = []
for i in range(0, num_iters + 1):
  start = 0
  start = i * 1500
  end = (i + 1) * 1500
  out = summarizer(result[start:end])
  out = out[0]
  out = out['summary_text']
  summarized_text.append(out)

print(summarized_text)

len(str(summarized_text))

from google.colab import drive
drive.mount('/content/drive')

str(summarized_text)

summarizer.save_pretrained('/content/drive/MyDrive/models')

